version: '3.9'
services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      bridge-net:
        ipv4_address: 172.28.0.2
    depends_on:
      - keycloak
  mariadb:
    image: mariadb
    restart: always
    container_name: mariadb
    environment:
      MARIADB_DATABASE: dbkc
      MARIADB_ROOT_PASSWORD: root
      MARIADB_PASSWORD: admin
      MARIADB_USER: admin
    ports:
      - 3306:3306
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      bridge-net:
        ipv4_address: 172.28.0.3

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    container_name: keycloak
    environment:
      KC_HOSTNAME: 172.28.0.4
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_DB: mariadb
      KC_DB_URL: jdbc:mariadb://mariadb:3306/dbkc?characterEncoding=UTF-8
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    command: start-dev
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    networks:
      bridge-net:
        ipv4_address: 172.28.0.4
networks:
  bridge-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1